### Note: DO NOT use quantized model or quantization_bit when merging lora adapters

### model
model_name_or_path: google/paligemma-3b-mix-224
visual_inputs: true
adapter_name_or_path: saves/paligemma-chat/checkpoint-10000
template: gemma
finetuning_type: lora

### export
export_dir: models/paligemma-3b-mix-224-vi-llava
export_size: 2
export_device: cpu
export_legacy_format: false

export_hub_model_id: hllj/paligemma-3b-mix-224-vi-llava