### model
model_name_or_path: google/paligemma-3b-mix-224
visual_inputs: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### ddp
ddp_timeout: 180000000

### dataset
dataset: identity,llava_vi_train
template: gemma
cutoff_len: 2048
overwrite_cache: true
cache_dir: /mnt/disks/dev/cache
preprocessing_num_workers: 16

### output
output_dir: saves/paligemma-chat
logging_steps: 10
save_steps: 10000
plot_loss: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 2
learning_rate: 0.00001
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_steps: 50
bf16: true

### eval
val_size: 0.01
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 1000

### logging
report_to: wandb
run_name: paligemma-3b-mix-224-vi-llava

resume_from_checkpoint: true